import type { Metadata } from 'next';
// import { AntdRegistry } from '@ant-design/nextjs-registry';
import './globals.css';
// import 'antd/dist/reset.css';
import 'antd/dist/antd.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <AntdRegistry>{children}</AntdRegistry> */}
        {children}
      </body>
    </html>
  );
}
